TECH_SYMBOLS = ['AAPL', 'MSFT', 'PYPL', 'TWTR', 'FB', 'GOOG', 'GME', 'ZM', 'SNAP', 'AMZN', 'WB', 'HUBS', 'SOCL', 'MOMO', 'SINA', 'NTES', 'MOXC', 'SRAX']

SOCIAL_MEDIA_SYMBOLS = [
  'WB', 'HUBS', 'SOCL', 'MOMO', 'SINA', 'NTES', 'MOXC', 'SRAX', 'LOV', 'FB',
  'SRT', 'IQ', 'HCHC', 'TWTR', 'EVC', 'MARK', 'BLIN', 'SNAP', 'GOOG', 'AMZN'
]

COMMON_RB_SYMBOLS = [
  'GE', 'RMBS', 'GDDY', 'FCEL', 'IPHI', 'CGNX', 'GOGO',
  'LLNW', 'CHT', 'NBIX', 'EXEL', 'FENG', 'CREE', 'CBMG',
  'TXN', 'BRKS', 'VNET', 'MLSS', 'JKS', 'BCOV', 'IDCC', 'AFMD',
  'ABM', 'USM', 'CTIC', 'VZ', 'OMER', 'AZN', 'NFLX', 'ARGX',
  'CPRT', 'MPWR', 'CAMP', 'NXPI', 'NKE', 'AKTX', 'OCUL', 'LQDT',
  'CIR', 'HEAR', 'UZC', 'BAC', 'MSFT', 'DHX', 'ASYS', 'BIIB', 'ILMN',
  'INFY', 'KF', 'ABBV', 'NK', 'NTES', 'CYTK', 'MEDP', 'ZSAN', 'MGIC',
  'GSK', 'CAMT', 'GNUS', 'RETA', 'SINA', 'PLUG', 'BCE', 'GRA', 'GUSH',
  'PXLW', 'ACB', 'USO', 'INSG', 'STRM', 'AOSL', 'EXAS', 'PKBK', 'FBIO',
  'GEVO', 'AMRX', 'UZA', 'CNSL', 'CGC', 'AAL', 'XPH', 'EMQQ', 'EXPE', 'SE',
  'AKRO', 'AMZN', 'GALT', 'MU', 'STM', 'SNDL', 'CVV', 'SPPI', 'XLRN',
  'ADIL', 'MRNA', 'BMRA', 'MXIM', 'NNDM', 'TWTR', 'EPAY', 'WOW', 'PYPL',
  'OFLX', 'AUDC', 'POWI', 'DBVT', 'DIS', 'UAL', 'FDNI', 'SHBI', 'JNJ',
  'PTC', 'ITCI', 'CMD', 'INCY', 'OPGN', 'UZB', 'MTSL', 'IT', 'PTE', 'MBOT',
  'HCHC', 'TSEM', 'ABNB', 'LE', 'DVAX', 'ZOM', 'VERI', 'PRAH', 'AWRE',
  'BKSC', 'ICPT', 'GTT', 'NETL', 'TSLA', 'KZR', 'AMBA', 'T', 'MBT', 'MANT',
  'TEF', 'UROV', 'CPST', 'TER', 'KO', 'OKTA', 'LIQT', 'MX', 'NWS', 'LEE',
  'KOS', 'VBLT', 'XPEV', 'LUV', 'LOV', 'CVM', 'ARKK', 'APTO', 'ICUI',
  'AMAT', 'CEVA', 'LI', 'AUPH', 'SNCA', 'TDE', 'VSH', 'CPIX', 'FREQ', 'TD',
  'VTVT', 'NKLA', 'UMC', 'CMI', 'TXMD', 'KVHI', 'WIX', 'AEYE', 'KRYS', 'AMC',
  'SAVE', 'FGBI', 'BA', 'INTC', 'MRVL', 'RCI', 'CAN', 'CMBM', 'SNAP', 'IYW',
  'AEIS', 'VIOT', 'SAVA', 'SAGE', 'AGLE', 'GMAB', 'ZNGA', 'DIOD', 'WFC',
  'DAL', 'EIDX', 'NIO', 'ET', 'FLOW', 'RVLV', 'GRVY', 'DNLI', 'ENDP',
  'ATOM', 'FLEX', 'AAPL', 'VOO', 'PKE', 'KLAC', 'GWW', 'CPSH', 'EA',
  'TBPH', 'BB', 'OPNT', 'PSTV', 'GPX', 'MRO', 'ABC', 'GSM', 'SVA', 'APLS',
  'SHEN', 'HIMX', 'CREX', 'ENZ', 'ALL', 'APM', 'IDEX', 'RUBY', 'VYGR', 'ADP', 
  'SRT', 'ALNY', 'GTN', 'HSKA', 'CWBR', 'BAND', 'CRWD', 'NRZ', 'XWEB', 'ABEO',
  'SLAB', 'BEAT', 'XBIT', 'V', 'F', 'ICHR', 'HBMD', 'MCRB', 'BMY', 'SNE',
  'IMGN', 'ATEC', 'SITM', 'NTNX', 'SMED', 'NVO', 'NWSA', 'AMD', 'TSM',
  'MDRX', 'PKX', 'TLSA', 'GSIT', 'KVH', 'MOXC', 'PLTR', 'BLIN', 'WKHS', 'WMT',
  'RAPT', 'SRAX', 'CSGP', 'RDUS', 'MRUS', 'CPRX', 'SIRI', 'CRUS', 'QDEL',
  'PRA', 'OIIM', 'MRSN', 'LOB', 'ADMS', 'VECO', 'VIR', 'AMKR', 'HWKN', 'ADMP',
  'VSAT', 'PSN', 'RYTM', 'ADXS', 'NVDA', 'DGII', 'WB', 'EVBG', 'PRPO', 'APTX',
  'GILD', 'ENPH', 'CRM', 'LSCC', 'BTAI', 'BABA', 'ADMA', 'LPLA', 'SNCR', 
  'CMCM', 'GRTX', 'AVT', 'NLTX', 'AVDL', 'APHA', 'SPI', 'SGH', 'SMH', 'PLAB',
  'INBK', 'CCL', 'MLND', 'GNAF', 'ADI', 'RIOT', 'FOXA', 'SQNS', 'IONS',
  'GRUB', 'PFE', 'MARA', 'GLW', 'FB', 'TRVN', 'SNN', 'CHRS', 'AT&T', 'ORAN',
  'QTT', 'SOCL', 'MLAB', 'QCOM', 'KLA', 'PSEC', 'CRON', 'KURA', 'IVR', 'SFET',
  'GME', 'XOM', 'PRVB', 'HEXO', 'IMOS', 'GM', 'NERV', 'EQ', 'INO', 'EQIX',
  'GPRO', 'BR', 'SMTC', 'SINT', 'DHI', 'FOX', 'IQ', 'SOXX', 'LKCO', 'SQ',
  'AMBO', 'HUBS', 'SJR', 'BZUN', 'ALLO', 'RZA', 'SOXL', 'OBLN', 'ANSS',
  'MIXT', 'XNCR', 'ASX', 'CCIV', 'OSUR', 'EVC', 'MRAM', 'MCHP', 'OCGN',
  'CBB', 'EBS', 'MFA', 'MOMO', 'UCTT', 'SWKS', 'LOGI', 'MARK', 'PBYI',
  'DSPG', 'MTSI', 'YEXT', 'BPMC', 'PCTY', 'NOK', 'NCLH', 'AVGO', 'MBIO',
  'WVE', 'PTON', 'SIMO', 'CWEB', 'MGM', 'WHLM', 'SNX', 'CRMD', 'BNGO',
  'JBLU', 'TNXP', 'ACER', 'SRNE', 'SIFY', 'VERU', 'CAPR', 'ECOM', 'URGN',
  'SY', 'TGTX', 'C-K', 'BLNK', 'MXL', 'QRVO', 'CYCN', 'KPTI', 'UBER',
]